name: config workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Grant Docker Permissions
      run: sudo chmod 666 /var/run/docker.sock
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run test with Gradle
      run: ./gradlew test --continue
    - name: Copy JAR artifact
      run: | 
        cp ./build/libs/config-service-0.0.1-SNAPSHOT.jar .
        ls .
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy with Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: yeison0720/configrepo:latest
