server:
  port: ${PORT:8081}
  address: 0.0.0.0
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Yeison07/config-server
          search-paths: config-data
  application:
    name: config-service