name: Project workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up OpenJDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run test with Gradle
      run: ./gradlew test --continue --test co.ufps.edu.userservice.* 
